export const IDENTITY_REPOSITORY = Symbol("IDENTITY_REPOSITORY");
export const BROADCAST_CAMPAIGN_REPOSITORY = Symbol("BROADCAST_CAMPAIGN_REPOSITORY");
export const BROADCAST_QUEUE_PORT = Symbol("BROADCAST_QUEUE_PORT");
export const BROADCAST_MESSAGE_SENDER_PORT = Symbol("BROADCAST_MESSAGE_SENDER_PORT");

export const CACHE_PORT = Symbol("CACHE_PORT");
export const CLOCK_PORT = Symbol("CLOCK_PORT");
export const ID_GENERATOR_PORT = Symbol("ID_GENERATOR_PORT");
export const IDEMPOTENCY_KEY_PORT = Symbol("IDEMPOTENCY_KEY_PORT");
export const JOB_DISPATCHER = Symbol("JOB_DISPATCHER");
export const LOGGER_PORT = Symbol("LOGGER_PORT");
export const RATE_LIMITER_PORT = Symbol("RATE_LIMITER_PORT");
export const TELEGRAM_IDEMPOTENCY_PORT = Symbol("TELEGRAM_IDEMPOTENCY_PORT");
export const TELEGRAM_SESSION_STORE_PORT = Symbol("TELEGRAM_SESSION_STORE_PORT");
export const TRANSACTION_MANAGER_PORT = Symbol("TRANSACTION_MANAGER_PORT");

export const REDIS_CLIENT = Symbol("REDIS_CLIENT");
export const POSTGRES_POOL = Symbol("POSTGRES_POOL");

export const TELEGRAM_COMMAND_HANDLERS = Symbol("TELEGRAM_COMMAND_HANDLERS");
